version: '3'

services:
  frontend_build:
    image: node:latest
    volumes:
      - ./client:/app
    command: sh -c "cd /app && (test -d build || (npm install && npm run build))"
  
  frontend:
    image: nginx:latest
    volumes:
      - ./client/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - frontend_build
    networks:
      - glocal

  backend:
    build: ./server
    volumes:
      - ./server/data:/app/data
    ports:
      - "5000:5000"
    restart: always
    environment:
      SCRIPT_NAME: /api
    networks:
      - glocal

networks:
  glocal:
