version: '3'

services:
  frontend_build:
    image: node:latest
    volumes:
      - ./client:/app
    command: sh -c "cd /app && (test -d build || (npm install && npm run build))"
  
  frontend:
    image: nginx:latest
    volumes:
      - ./client/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8085:80"
      - "8086:443"
    environment:
      VIRTUAL_HOST: report.azaleaupv.com
    restart: always
    depends_on:
      - frontend_build

  backend:
    build: ./server
    volumes:
      - ./server/data:/app/data
    ports:
      - "5050:5000"
    restart: always
    command: gunicorn -w 4 --certfile data/cert.pem --keyfile data/privkey.pem  -b 0.0.0.0:5000 app:app 